// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Paulo Henrique Gomes Pinto",
            "url": "https://github.com/paulo-henrique-ph/v2v-blockchain-security",
            "email": "via GitHub Issues"
        },
        "license": {
            "name": "GNU General Public License v2.0",
            "url": "https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the gateway is running and operational",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Gateway is healthy",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.HealthResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "post": {
                "description": "Process a V2X message with validation, security checks, and blockchain submission\n\nThe message will be validated for:\n- Digital signature authenticity\n- Replay attack prevention\n- Plausibility checks (coordinates, timestamp)\n\nCritical messages (priority 0-1, emergency types) are immediately submitted to blockchain.\nNon-critical messages are aggregated for batch processing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Process V2X message",
                "parameters": [
                    {
                        "description": "V2X Message",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.V2XMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message processed and submitted to blockchain",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.ProcessingResult"
                        }
                    },
                    "202": {
                        "description": "Message accepted for aggregation",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.ProcessingResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Retrieve processing statistics including message counts, latencies, and throughput",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get gateway statistics",
                "responses": {
                    "200": {
                        "description": "Gateway statistics",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_adapters_rest.StatisticsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infrastructure_adapters_rest.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request body"
                },
                "message": {
                    "type": "string",
                    "example": "messageId is required"
                }
            }
        },
        "internal_infrastructure_adapters_rest.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-03-03T10:00:00Z"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m15s"
                }
            }
        },
        "internal_infrastructure_adapters_rest.ProcessingResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                },
                "latency": {
                    "type": "integer",
                    "example": 45
                },
                "messageId": {
                    "type": "string",
                    "example": "MSG-001"
                },
                "reason": {
                    "type": "string",
                    "example": "Invalid signature"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "submitted",
                        "aggregated",
                        "rejected"
                    ],
                    "example": "submitted"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-03-03T10:00:00Z"
                },
                "txHash": {
                    "type": "string",
                    "example": "0x1234567890abcdef"
                }
            }
        },
        "internal_infrastructure_adapters_rest.StatisticsResponse": {
            "type": "object",
            "properties": {
                "avgLatencyMs": {
                    "type": "number",
                    "example": 42.5
                },
                "totalAggregated": {
                    "type": "integer",
                    "example": 350
                },
                "totalReceived": {
                    "type": "integer",
                    "example": 1000
                },
                "totalRejected": {
                    "type": "integer",
                    "example": 50
                },
                "totalSubmitted": {
                    "type": "integer",
                    "example": 600
                },
                "totalValidated": {
                    "type": "integer",
                    "example": 950
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m15s"
                }
            }
        },
        "internal_infrastructure_adapters_rest.V2XMessageRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude",
                "messageId",
                "messageType",
                "priority",
                "senderId",
                "signature",
                "timestamp"
            ],
            "properties": {
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90,
                    "example": -23.5505
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180,
                    "example": -46.6333
                },
                "messageId": {
                    "type": "string",
                    "example": "MSG-001"
                },
                "messageType": {
                    "type": "string",
                    "enum": [
                        "CAM",
                        "DENM",
                        "SPAT",
                        "MAP",
                        "EMERGENCY_BRAKE",
                        "COLLISION_WARNING",
                        "TRAFFIC_UPDATE",
                        "ROAD_HAZARD"
                    ],
                    "example": "EMERGENCY_BRAKE"
                },
                "metadata": {
                    "type": "object"
                },
                "priority": {
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0,
                    "example": 0
                },
                "senderId": {
                    "type": "string",
                    "example": "VEHICLE-001"
                },
                "signature": {
                    "type": "string",
                    "example": "base64encodedSignature=="
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-03-03T10:00:00Z"
                }
            }
        }
    },
    "tags": [
        {
            "description": "V2X message processing endpoints",
            "name": "Messages"
        },
        {
            "description": "Health check and statistics endpoints",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "V2X Gateway RSU API",
	Description:      "High-performance V2X Gateway RSU for secure vehicle-to-infrastructure communication with blockchain integration\n\nThis API provides endpoints for:\n- Processing V2X messages (CAM, DENM, SPAT, MAP)\n- Message validation and security checks\n- Blockchain integration for immutable audit trails\n- Real-time statistics and health monitoring",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
