// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: internal/infrastructure/adapters/grpc/v2x.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// V2X Message Request
type V2XMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId   string            `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType string            `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	SenderId    string            `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp   string            `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Priority    int32             `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Latitude    float64           `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude   float64           `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Signature   string            `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Metadata    map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *V2XMessageRequest) Reset() {
	*x = V2XMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V2XMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V2XMessageRequest) ProtoMessage() {}

func (x *V2XMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *V2XMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *V2XMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *V2XMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *V2XMessageRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *V2XMessageRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *V2XMessageRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *V2XMessageRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *V2XMessageRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *V2XMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Batch Request
type BatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*V2XMessageRequest `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchRequest) GetMessages() []*V2XMessageRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Processing Response
type ProcessingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash    string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MessageId string `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Latency   int64  `protobuf:"varint,6,opt,name=latency,proto3" json:"latency,omitempty"`
	Reason    string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Error     string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProcessingResponse) Reset() {
	*x = ProcessingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingResponse) ProtoMessage() {}

func (x *ProcessingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcessingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessingResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ProcessingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessingResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ProcessingResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ProcessingResponse) GetLatency() int64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ProcessingResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProcessingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Statistics Response
type StatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMessages      int64             `protobuf:"varint,1,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	CriticalMessages   int64             `protobuf:"varint,2,opt,name=critical_messages,json=criticalMessages,proto3" json:"critical_messages,omitempty"`
	MessagesPerSecond  int64             `protobuf:"varint,3,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"`
	AggregatedMessages int64             `protobuf:"varint,4,opt,name=aggregated_messages,json=aggregatedMessages,proto3" json:"aggregated_messages,omitempty"`
	AvgLatency         float64           `protobuf:"fixed64,5,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	Uptime             string            `protobuf:"bytes,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	MessageTypes       map[string]int64  `protobuf:"bytes,7,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatisticsResponse) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *StatisticsResponse) GetCriticalMessages() int64 {
	if x != nil {
		return x.CriticalMessages
	}
	return 0
}

func (x *StatisticsResponse) GetMessagesPerSecond() int64 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *StatisticsResponse) GetAggregatedMessages() int64 {
	if x != nil {
		return x.AggregatedMessages
	}
	return 0
}

func (x *StatisticsResponse) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

func (x *StatisticsResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *StatisticsResponse) GetMessageTypes() map[string]int64 {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

// Health Response
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version    string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp  string            `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Components map[string]string `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

// Empty message for requests with no parameters
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_infrastructure_adapters_grpc_v2x_proto_goTypes = []interface{}{
	(*V2XMessageRequest)(nil),  // 0: v2x.V2XMessageRequest
	(*BatchRequest)(nil),       // 1: v2x.BatchRequest
	(*ProcessingResponse)(nil), // 2: v2x.ProcessingResponse
	(*StatisticsResponse)(nil), // 3: v2x.StatisticsResponse
	(*HealthResponse)(nil),     // 4: v2x.HealthResponse
	(*Empty)(nil),              // 5: v2x.Empty
	nil,                        // 6: v2x.V2XMessageRequest.MetadataEntry
	nil,                        // 7: v2x.StatisticsResponse.MessageTypesEntry
	nil,                        // 8: v2x.HealthResponse.ComponentsEntry
}

var file_internal_infrastructure_adapters_grpc_v2x_proto_depIdxs = []int32{
	0, // 0: v2x.BatchRequest.messages:type_name -> v2x.V2XMessageRequest
	6, // 1: v2x.V2XMessageRequest.metadata:type_name -> v2x.V2XMessageRequest.MetadataEntry
	7, // 2: v2x.StatisticsResponse.message_types:type_name -> v2x.StatisticsResponse.MessageTypesEntry
	8, // 3: v2x.HealthResponse.components:type_name -> v2x.HealthResponse.ComponentsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_adapters_grpc_v2x_proto_init() }
func file_internal_infrastructure_adapters_grpc_v2x_proto_init() {
	if protoimpl.UnsafeEnabled {
		file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V2XMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_infrastructure_adapters_grpc_v2x_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_adapters_grpc_v2x_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_adapters_grpc_v2x_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_adapters_grpc_v2x_proto_msgTypes,
	}.Build()
	file_internal_infrastructure_adapters_grpc_v2x_proto_rawDesc = nil
	file_internal_infrastructure_adapters_grpc_v2x_proto_goTypes = nil
	file_internal_infrastructure_adapters_grpc_v2x_proto_depIdxs = nil
}

var file_internal_infrastructure_adapters_grpc_v2x_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x76, 0x32, 0x78, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x68,
	0x67, 0x70, 0x2f, 0x76, 0x32, 0x78, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x72,
	0x73, 0x75, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}
