// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: internal/infrastructure/adapters/grpc/v2x.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	V2XService_ProcessMessage_FullMethodName = "/v2x.V2XService/ProcessMessage"
	V2XService_ProcessBatch_FullMethodName   = "/v2x.V2XService/ProcessBatch"
	V2XService_GetStatistics_FullMethodName  = "/v2x.V2XService/GetStatistics"
	V2XService_HealthCheck_FullMethodName    = "/v2x.V2XService/HealthCheck"
	V2XService_StreamMessages_FullMethodName = "/v2x.V2XService/StreamMessages"
)

// V2XServiceClient is the client API for V2XService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type V2XServiceClient interface {
	// Process a single V2X message
	ProcessMessage(ctx context.Context, in *V2XMessageRequest, opts ...grpc.CallOption) (*ProcessingResponse, error)
	// Process batch of V2X messages
	ProcessBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*ProcessingResponse, error)
	// Get gateway statistics
	GetStatistics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatisticsResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Streaming: continuous message processing
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (V2XService_StreamMessagesClient, error)
}

type v2xServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewV2XServiceClient(cc grpc.ClientConnInterface) V2XServiceClient {
	return &v2xServiceClient{cc}
}

func (c *v2xServiceClient) ProcessMessage(ctx context.Context, in *V2XMessageRequest, opts ...grpc.CallOption) (*ProcessingResponse, error) {
	out := new(ProcessingResponse)
	err := c.cc.Invoke(ctx, V2XService_ProcessMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v2xServiceClient) ProcessBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*ProcessingResponse, error) {
	out := new(ProcessingResponse)
	err := c.cc.Invoke(ctx, V2XService_ProcessBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v2xServiceClient) GetStatistics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatisticsResponse, error) {
	out := new(StatisticsResponse)
	err := c.cc.Invoke(ctx, V2XService_GetStatistics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v2xServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, V2XService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v2xServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (V2XService_StreamMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &V2XService_ServiceDesc.Streams[0], V2XService_StreamMessages_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &v2xServiceStreamMessagesClient{stream}
	return x, nil
}

type V2XService_StreamMessagesClient interface {
	Send(*V2XMessageRequest) error
	Recv() (*ProcessingResponse, error)
	grpc.ClientStream
}

type v2xServiceStreamMessagesClient struct {
	grpc.ClientStream
}

func (x *v2xServiceStreamMessagesClient) Send(m *V2XMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *v2xServiceStreamMessagesClient) Recv() (*ProcessingResponse, error) {
	m := new(ProcessingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// V2XServiceServer is the server API for V2XService service.
// All implementations must embed UnimplementedV2XServiceServer
// for forward compatibility
type V2XServiceServer interface {
	// Process a single V2X message
	ProcessMessage(context.Context, *V2XMessageRequest) (*ProcessingResponse, error)
	// Process batch of V2X messages
	ProcessBatch(context.Context, *BatchRequest) (*ProcessingResponse, error)
	// Get gateway statistics
	GetStatistics(context.Context, *Empty) (*StatisticsResponse, error)
	// Health check
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	// Streaming: continuous message processing
	StreamMessages(V2XService_StreamMessagesServer) error
	mustEmbedUnimplementedV2XServiceServer()
}

// UnimplementedV2XServiceServer must be embedded to have forward compatible implementations.
type UnimplementedV2XServiceServer struct {
}

func (UnimplementedV2XServiceServer) ProcessMessage(context.Context, *V2XMessageRequest) (*ProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedV2XServiceServer) ProcessBatch(context.Context, *BatchRequest) (*ProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedV2XServiceServer) GetStatistics(context.Context, *Empty) (*StatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedV2XServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedV2XServiceServer) StreamMessages(V2XService_StreamMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedV2XServiceServer) mustEmbedUnimplementedV2XServiceServer() {}

// UnsafeV2XServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V2XServiceServer will
// result in compilation errors.
type UnsafeV2XServiceServer interface {
	mustEmbedUnimplementedV2XServiceServer()
}

func RegisterV2XServiceServer(s grpc.ServiceRegistrar, srv V2XServiceServer) {
	s.RegisterService(&V2XService_ServiceDesc, srv)
}

func _V2XService_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V2XMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V2XServiceServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V2XService_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V2XServiceServer).ProcessMessage(ctx, req.(*V2XMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V2XService_ProcessBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V2XServiceServer).ProcessBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V2XService_ProcessBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V2XServiceServer).ProcessBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V2XService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V2XServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V2XService_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V2XServiceServer).GetStatistics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _V2XService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V2XServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V2XService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V2XServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _V2XService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(V2XServiceServer).StreamMessages(&v2xServiceStreamMessagesServer{stream})
}

type V2XService_StreamMessagesServer interface {
	Send(*ProcessingResponse) error
	Recv() (*V2XMessageRequest, error)
	grpc.ServerStream
}

type v2xServiceStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *v2xServiceStreamMessagesServer) Send(m *ProcessingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *v2xServiceStreamMessagesServer) Recv() (*V2XMessageRequest, error) {
	m := new(V2XMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// V2XService_ServiceDesc is the grpc.ServiceDesc for V2XService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V2XService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2x.V2XService",
	HandlerType: (*V2XServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _V2XService_ProcessMessage_Handler,
		},
		{
			MethodName: "ProcessBatch",
			Handler:    _V2XService_ProcessBatch_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _V2XService_GetStatistics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _V2XService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _V2XService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/infrastructure/adapters/grpc/v2x.proto",
}
